project_name  = "stage"
cidr_block    = "10.0.0.0/16"
key_pair_name = "devops-key"
eks_name      = "bilarn-cluster"
zone1         = "us-east-1a"
zone2         = "us-east-1b"
region        = "us-east-1"
env           = "development"
eks_version   = "1.33"

