# project_name  = "mernstck"
# cidr_block    = "10.0.0.0/16"
# key_pair_name = "ec2-aws-key"
# eks_name      = "bilarn-cluster"
# zone1         = "us-east-1a"
# zone2         = "us-east-1b"
# region        = "us-east-1"
# env           = "dev"
# eks_version   = "1.30"

